name: pyapprox-base
channels:
  - defaults
  - conda-forge
dependencies:
  - python>3.6
  - numpy>=1.20
  - matplotlib
  - scipy
  - jupyter
  - pytest
  - pytest-cov
  - pip
  - setuptools
  - scikit-learn
  - Cython
  - sympy
  - networkx
  - pytorch
  - numba
  # make html in docs folder
  - sphinx
  - sphinx-gallery
  - pip:
    - scikit-fem
    - sphinx_copybutton
    - sphinx_rtd_theme
    - numpydoc
    - sphinx_automodapi
